data:
  name: 'TUM_xyz'
  data_path: 'data'
  augmentation:
    photometric:
      enable: true
      primitives: [
        'random_brightness', 'random_contrast', 'additive_speckle_noise',
        'additive_gaussian_noise', 'additive_shade', 'motion_blur']
      params:
        random_brightness: {max_abs_change: 50}
        random_contrast: {strength_range: [0.5, 1.5]}
        additive_gaussian_noise: {stddev_range: [0, 10]}
        additive_speckle_noise: {prob_range: [0, 0.0035]}
        additive_shade:
          transparency_range: [-0.5, 0.5]
          kernel_size_range: [100, 150]
        motion_blur: {max_kernel_size: 3}
    homographic:
      enable: false
  warped_pair:
    params:
      translation: true
      rotation: true
      scaling: true
      perspective: true
      scaling_amplitude: 0.2
      perspective_amplitude_x: 0.2
      perspective_amplitude_y: 0.2
      patch_ratio: 0.85
      max_angle: 1.57
      allow_artifacts: true
    valid_border_margin: 3
model:
  name: 'super_point'
  grid_size: 8
  descriptor_size: 16
  batch_size: 3
  eval_batch_size: 3
  learning_rate: 0.0001
  lambda_d: 800
  positive_margin: 1
  negative_margin: 0.2
  lambda_loss: 1
  detection_threshold: 0.5
experiment:
  name: 'SuperPoint'
  num_epochs: 17000
  seed: 12
  save_interval: 25
  checkpoints_path: 'checkpoints'
  keep_checkpoints: 6
  load_checkpoints: false
  load_checkpoint_iter: 20
  logs_path: 'logs'