data:
    name: 'synthetic_shapes'
    data_path: ''
    primitives: 'all'
    truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
    cache_in_memory: true
    validation_size: 30
    test_size: 50
    suffix: 'v1'
    preprocessing:
        blur_size: 21
        resize: [120, 160]
    generation:
        split_sizes: {training: 5, validation: 5, test: 5}
        image_size: [960, 1280]
        random_seed: 0
        params:
            generate_background:
              {min_kernel_size: 150, max_kernel_size: 500,
               min_rad_ratio: 0.02, max_rad_ratio: 0.031}
            draw_stripes: {transform_params: [0.1, 0.1]}
            draw_multiple_polygons: {kernel_boundaries: [50, 100]}
    augmentation:
        photometric:
            enable: false
        homographic:
            enable: false
model:
    name: 'magic_point'
    batch_size: 64
    eval_batch_size: 50
    learning_rate: 0.001
    kernel_reg: 0.
    detection_threshold: 0.001 # 1/65
    nms: 4
train_iter: 200000
eval_iter: 200
validation_interval: 1000
seed: 12
#save_interval: 5000
#keep_checkpoints: 20