data:
  name: ['TUM_xyz', 'synthetic_shapes']
  data_path: '../data'
  primitives: 'all'
  truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
  suffix: 'train'
model:
  name: 'magic_point'
  batch_size: 1
  grid_size: 8
  detection_threshold: 0.6
  nms: 8
  iou_threshold: 0.1
  top_k: 0
  homography_adaptation:
    num: 100
    aggregation: 'sum'
    homographies:
      translation: true
      rotation: true
      scaling: true
      perspective: true
      scaling_amplitude: 0.2
      perspective_amplitude_x: 0.2
      perspective_amplitude_y: 0.2
      allow_artifacts: true
      patch_ratio: 0.85
experiment:
  name: 'Export'
  seed: 24
  checkpoints_path: '../../common/checkpoints'
  load_checkpoints: true
  load_checkpoint_iter: 1500